Slimes + Couple Fixes
ix0rai/rainglow pull request #12
Opened 2023-04-11 17:45 UTC by A5ho9999

- Added Slimes
- Added Allay Clone Support (Config Option if possible?)
- Updated Green texture for Allay, it was too washed out for my taste

- Adds Lots of TODOs around for things that could be better/changed/cleaned up

Hopefully the Todo's are helpful for cleaning up after me and not just annoying, tried to keep this one more to your style.

- [ ] Slimes need Particles - Currently just not doing any but the mixin is provided for it
- [ ] Maybe make the Black Slime texture better, It does look horrible

2023-04-11 17:58 UTC, A5ho9999 commented on src/main/resources/assets/minecraft/textures/entity/slime/slime.psd
whoops, this wasn't meant to be added, but at least you might be able to fix the black lol

2023-04-12 18:16 UTC, ix0rai requested changes
seeing a few issues with this, are you planning on doing any more work or should I merge and do things myself?

2023-04-12 18:16 UTC, ix0rai commented on src/main/java/io/ix0rai/rainglow/mixin/SlimeEntityMixin.java
> +    @Inject(method = "remove", at = @At("HEAD"), cancellable = true)
this mixin feels a bit extra, can you not run an `@ModifyVariable` on the new `SlimeEntity`?

2023-04-12 18:16 UTC, ix0rai commented on src/main/java/io/ix0rai/rainglow/mixin/AllayEntityMixin.java
> +    @Inject(method = "method_44363", at = @At("HEAD"), cancellable = true)
same thing here, I feel like this could be less intrusive
"inject head unconditional cancel" is a bit of a meme since it's just an @Overwrite that won't raise conflicts

2023-04-13 05:18 UTC, A5ho9999 commented
> seeing a few issues with this, are you planning on doing any more work or should I merge and do things myself?

It may honestly be best if you did them yourself, I'd most likely just mess something up if I tried right now

2023-04-16 00:52 UTC, merged