French Translation
ix0rai/rainglow pull request #20
Opened 2023-10-07 01:14 UTC by Desoroxxx

Thought a French translation could be nice, so I did one

2023-10-07 23:01 UTC, ix0rai requested changes

2023-10-07 23:01 UTC, ix0rai commented on src/main/resources/assets/rainglow/lang/fr_fr.json
> +  "rainglow.config.more": "plus",
```suggestion
  "rainglow.config.more": "Plus",
```

2023-10-08 16:39 UTC, Desoroxxx commented on src/main/resources/assets/rainglow/lang/fr_fr.json
> +  "rainglow.config.more": "plus",
I tried being faithful to the original translation, which did not have capitalization there but it guess it was a mistake, could I get confirmation it was a mistake?
https://github.com/ix0rai/rainglow/blob/master/src/main/resources/assets/rainglow/lang/en_us.json#L5

2023-10-08 16:55 UTC, ix0rai commented on src/main/resources/assets/rainglow/lang/fr_fr.json
> +  "rainglow.config.more": "plus",
yes, my mistake
I'll fix that today

2023-10-08 17:36 UTC, Desoroxxx commented on src/main/resources/assets/rainglow/lang/fr_fr.json
> +  "rainglow.config.more": "plus",
> yes, my mistake I'll fix that today

Okay, merged the suggestion

2023-10-08 17:41 UTC, merged